# Generated by Django 2.2.16 on 2020-11-08 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 8, 16, 46, 33, 934548), verbose_name='Опубликована'),
        ),
    ]
