# Generated by Django 2.2.16 on 2020-11-09 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201109_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 9, 19, 55, 18, 275973), verbose_name='Опубликована'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
