# Generated by Django 2.2.16 on 2020-11-18 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201118_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(default='none.txt', upload_to='', verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 18, 19, 44, 27, 623353), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 18, 19, 44, 27, 624354), verbose_name='Дата'),
        ),
    ]
